config/routes.rb
Rails.application.routes.draw do
  get 'simple_sessions/create'
  post 'simple_sessions/clear'

#  get 'emailadd/sendbyemail'
#  post 'emailadds/sendbyemail'
  post 'books/notify'
  post 'writers/update'

  get 'books/new'
#  resources :books

  post 'books', to: 'books#new'
  patch 'books/:id/', to: 'books#update'
#  post 'books/send', to: 'books#sendbyemail'
  post '/login', to: 'simple_sessions#create'
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @book = Book.last
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if flash[:alert]%>
<div id=flash><%= flash[:alert] unless flash[:alert].blank?%></div>
<%end%>
<div id="titleCont">
  <h1>debrief</h1>
</div>
<% if logged_in? %>

<div id = "createCont">

  <div id="create_author">
    <h2>new author</h2>
    <% @new_author = Book.new %>
    <%= form_for(@new_author, url: books_path, method: 'post', ) do |f| %>

    <p class="autorImePrezime">
      <%= f.label :autorIme, "ime autora" %><br>
      <%= f.text_field :autorIme %>
    </p>
    <p class="autorImePrezime">
      <%= f.label :autorPrezime, "prezime" %><br>
      <%= f.text_field :autorPrezime %>
    </p>
    <p class="dugmad">
      <%= f.submit 'create new author' %>
    </p>
    <% end %>
  </div>
  <div id="create">
    <h2>new book</h2>
    <% @new_book = Book.new %>
    <%= form_for(@new_book, url: books_path, method: 'post') do |f| %>
    <p>
      <%= f.label :title, "naslov" %><br>
      <%= f.text_field :title %>
    </p>
    <p class="autorImePrezime">
      <%= f.label :autorIme, "ime autora" %><br>
      <%= f.text_field :autorIme %>
    </p>
    <p class="autorImePrezime">
      <%= f.label :autorPrezime, "prezime" %><br>
      <%= f.text_field :autorPrezime %>
    </p>
    <p class="dugmad">
      <%= f.submit 'create new book' %>
    </p>
    <% end %>
  </div>

  <div id="uputstvo_notify">
    <ul>
      <li>koriste se čćđšž, italic se označava zvezdicama (objavila roman *Always a lizard*)</li>
      <li>kroz polja može da se šeta pritiskanjem tab-a, ne mora da se klikće mišem</li>
      <li>formular iznad služi za dodavanje <span>nove</span> knjige (autora) i brisanje <span>aktuelne</span>, formular ispod za unos podataka o <span>aktuelnoj</span> knjizi (autoru)</li>
    </ul>
  </div>
</div>



<div id=updateCont>
  <%= form_for(@book, url: 'books/'+@book.id.to_s) do |f| %>
  <% if @book.title != "x"  %>
  <div id="form_book">
    <h2><%= @book.title %></h2>
    <% if @book.title == "oh, pear"%>
    <fieldset disabled>
      <% end %>

      <p>
        <%= f.label :oknjizi, 'o knjizi' %><br>
        <%= f.text_area :oknjizi, :spellcheck =>"false" %>
      </p>
      <p>
        <%= f.label :odlomak, 'odlomak' %><br>
        <%= f.text_area :odlomak, :spellcheck =>"false"  %>
      </p>
      <div id=inform_cont>
        <div class="levo">
          <p id="book_isbn_p">
            <%= f.label :isbn, 'isbn'%><br>
            <%= f.text_field :isbn %>
          </p>
          <p id="book_prevod_p">
            <%= f.label :prevod, 'prevod'%><br>
            <%= f.text_field :prevod %>
          </p>
          <p>
            <%= f.label :pogovor, 'pogovor'%><br>
            <%= f.text_field :pogovor %>
          </p>
          <p>
            <%= f.label :potpis, 'pogovor - za korice'%>
            <%= f.text_field :potpis %>
          </p>
          <p >
            <%= f.label :unajavi, 'u najavi'%><br>
            <%= f.text_field :unajavi %>
          </p>
        </div>
        <div class="desno">
          <p id="book_cena_p">
            <%= f.label :cena, 'cena'%><br>
            <%= f.text_field :cena %>
          </p>
          <p >
            <%= f.label :broj_strana, 'br. str.'%><br>
            <%= f.text_field :broj_strana %>
          </p>

          <p>
            <%= f.label :broj_strana_odlomak, 'str. odl.'%><span class="expl">?<span>koliko strana za odlomak (pdf)</span></span><br>
            <%= f.text_field :broj_strana_odlomak %>
          </p>
        </div>

        <div class="desno">
          <p>
            <%= f.label :visina, 'visina'%><br>
            <%= f.text_field :visina %>
          </p>
          <p>
            <%= f.label :sirina, 'širina'%><br>
            <%= f.text_field :sirina%>
          </p>
          <p>
            <%= f.label :klapna, 'klapna'%><br>
            <%= f.text_field :klapna %>
          </p>
        </div>
      </div>
      <% if @book.title == "oh, pear"%>
    </fieldset disabled>
    <% end %>
  </div>
  <% end %>

  <div id="form_author">
    <div id="lekt">
      <% if @book.bio_lekt %>
      <%= boldicize(@book.bio_lekt).html_safe%>

      <%end%>
    </div>
    <% if Writer.find_by(name: @book.autorIme + " " + @book.autorPrezime) %>
    <fieldset disabled>
      <%end %>
      <h2><%= @book.autorIme + " " + @book.autorPrezime %> </h2>
      <p>
        <div id="lekt_butt"> show prev. edit </div>
        <%= f.label :bio, 'bio'%><br>
        <%= f.text_area :bio, :spellcheck =>"false"  %>
      </p>
      <p>
        <%= f.label :kontakt, 'kontakt'%><br>
        <%= f.text_field :kontakt %>
      </p>
      <p>
        <%= f.label :wiki, 'wiki'%><br>
        <%= f.text_field :wiki %>
      </p>
      <p>
        <%= f.label :goodreads, 'goodreads'%><br>
        <%= f.text_field :goodreads %>
      </p>
      <p>
        <%= f.label :orig_ime, 'ime u originalu'%><br>
        <%= f.text_field :orig_ime %>
      </p>
      <% if !Writer.find_by(name: @book.autorIme + " " + @book.autorPrezime) %>
      <fieldset disabled>
        <%end %>
      </div>

      <div id="spacer"></div>

      <p class="dugmad">
        <%= f.submit('save') %>
      </p>
      <p class="dugmad"><%= f.submit "send by e-mail", name: 'email'%></p>

      <% end %>
      <div id = "uputstvo_notify">
        <ul>
          <li>Dugme 'send by email' šalje fajl sa svim podacima Sonji. Ako hoćete da pošaljete neko obaveštenje (npr. Srđane, lektorisano je, rekla sam ti 100 puta da se 'ne vidi' piše odvojeno), u formularu ispod se kuca tekst i biraju primaoci.</li>
        </ul>
      </div>
    </div>


    <div id="notifyCont">

      <% @mails = Emailadd.pluck(:name,:id, :checked) %>
      <%= form_tag(books_notify_path, method: 'post', id:"form_notify") do %>
      <h2 id="h2_notify">notify</h2>

      <div id="select_mail">
        <% @mails.each do |m|%>
        <p>
          <% if m[2] %>
          <%= check_box_tag(m[0],m[1],checked=true)%>
          <% else %>
          <%= check_box_tag(m[0],m[1],checked=false)%>
          <%end%>
          <%= label_tag(m[0],m[0]) %>
        </p>
        <%end%>
      </div>
      <div id="create_mail">
        <p>
          <%= label_tag ("subject")%><br>
          <%= text_field_tag("sabdzekt") %>
        </p>
        <p>
          <%= label_tag ("content")%><br>
          <%= text_area_tag "tekst" %>
        </p>


        <p class="dugmad">
          <%=submit_tag("send")%>
        </p>

        <%tmp = @mails.map{|mm| [mm[0], mm[0]]}.insert(0,["sender","nil"]) %>
        <p id="sender_cont">
          <%=select_tag(:sender, options_for_select(tmp))%>
        </p>

      </div>

      <%end%>


    </div>



    <div id="luft"></div>

    <% else %>
    <div id="login">
      <%= form_for(:session, url:login_path) do |f| %>
      <%= f.label :password %><br>
      <%= f.password_field :password %><br>
      <p class="dugmad">
        <%= f.submit "log in" %>
        <% end %>
      </p>
    </div>
    <% end %>

    <script>
    lb = document.getElementById("lekt_butt");
    lb.onclick = function(e) {
      document.getElementById("lekt").classList.toggle("display");
      e.stopPropagation();
    }
    document.onclick = function() {
      document.getElementById("lekt").classList.remove("display");
    }

    document.getElementById("lekt").onclick = function(e) {
      e.stopPropagation();
    }
    </script>